name       : atomicparsley
version    : 0.9.6
release    : 1
source     :
    - https://bitbucket.org/wez/atomicparsley/get/0.9.6.tar.bz2 : e28d46728be86219e6ce48695ea637d831ca0170ca6bdac99810996a8291ee50
license    : GPL-2.0
component  : multimedia.video
summary    : AtomicParsley is a program for manipulating metadata within MPEG-4 files
description: |
    AtomicParsley is a lightweight command line program for reading, parsing and setting metadata into MPEG-4 files, in particular, iTunes-style metadata.
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
