name       : atomicparsley
version    : '20210715'
release    : 2
source     :
    - https://github.com/wez/atomicparsley/archive/refs/tags/20210715.151551.e7ad03a.tar.gz : 546dcb5f3b625aff4f6bf22d27a0a636d15854fd729402a6933d31f3d0417e0d
homepage   : https://github.com/wez/atomicparsley
license    : GPL-2.0-or-later
component  : multimedia.video
summary    : A program for manipulating metadata within MPEG-4 files
description: |
    AtomicParsley is a lightweight command line program for reading, parsing and setting metadata into MPEG-4 files, in particular, iTunes-style metadata.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
